typer on ga schedule script
Axiom-Cloud-Inc/operator-toolkit pull request #13
Opened 2021-07-12 22:37 UTC by JulianaCP-v2

2021-07-12 22:49 UTC, samhollenbach approved these changes

2021-07-12 22:49 UTC, samhollenbach commented on operator_toolkit/create_soc_percentile.py
> +                                                        config=CONFIG)
Seems like a flake8 violation

2021-07-12 22:56 UTC, JulianaCP-v2 commented on operator_toolkit/create_soc_percentile.py
> +                                                        config=CONFIG)
you're right, thanks 👌

2021-07-12 22:58 UTC, lucasmlofaro requested changes

2021-07-12 22:58 UTC, lucasmlofaro commented on operator_toolkit/operation/utils.py
> +
So the result of having this `load_file()` method be nullable (can return something falsy) is that you're able to play this trick where you exit early if you find the local file and only attempt the S3 load if you make it there. This works, but you've violated DRY, it's almost the exact same snippet.

Ideally, we should make one assignment and one conditional return. We can leverage the short-circuit nature of boolean expressions (lazy evaluation) to achieve the same thing as the early exit.
```suggestion
        # load config with operational sites
        config = (FileManager.load_file(OPERATIONAL_SITES_LOCAL_PATH) or
                  FileManager.load_file(OPERATIONAL_SITES_S3_PATH))
        if config:
            ...  # deal with failed config loading
        return config

```

The other thing to note is that I typically prefer to have the "happy path" return be the default and use conditionals to do error handling.

2021-07-12 22:58 UTC, lucasmlofaro commented on operator_toolkit/main.py
> +app.add_typer(ga_schedule.app, name="ga_schedule")
I think I understand what you were talking about before now. This is the typical pattern for separating subcommands across modules?

2021-07-12 22:58 UTC, lucasmlofaro commented on operator_toolkit/ga_schedule.py
> +    }
These are potentially good places to add some structure to the data. Maybe some kind of `Report` object that has some `display()` method?

2021-07-12 22:59 UTC, lucasmlofaro commented on operator_toolkit/create_soc_percentile.py
> +                                                        config=CONFIG)
Yeah! I was actually gonna say, @JulianaCP-v2 maybe one task you can do this sprint would be add this repo to CircleCI.

2021-07-12 22:59 UTC, JulianaCP commented on operator_toolkit/main.py
> +app.add_typer(ga_schedule.app, name="ga_schedule")
yes, exactly

2021-07-12 23:00 UTC, JulianaCP commented on operator_toolkit/operation/utils.py
> +
mmm nice, I like it, thanks 👌

2021-07-12 23:07 UTC, JulianaCP commented on operator_toolkit/ga_schedule.py
> +    }
mm sounds nice 🤔 will try to think in a fancy way to implement something like this, thanks

2021-07-13 17:44 UTC, lucasmlofaro approved these changes
Looks good

2021-07-13 17:45 UTC, merged