Auto, mode check and forecast scripts
Axiom-Cloud-Inc/operator-toolkit pull request #15
Opened 2021-07-14 16:09 UTC by JulianaCP-v2

- typer added to the auto-check script, the mode script, and the forecast script.

2021-07-15 06:23 UTC, lucasmlofaro requested changes

2021-07-15 06:23 UTC, lucasmlofaro commented on operator_toolkit/check_auto.py
> +                all_auto = True if circuits_on_auto and compressors_on_auto else False
An expression like 
```python
True if proposition else False
```
is equivalent to the proposition itself (or its boolean value to be more precise for Python)

 ```suggestion
                 all_auto = bool(circuits_on_auto and compressors_on_auto)
```

2021-07-15 06:23 UTC, lucasmlofaro commented on operator_toolkit/check_auto.py
> +class AutoReportManager:
I don't quite understand the abstraction here. It seems like the idea is wrap something around a `Report` object so it can handle multiple sites, but it feels a bit awkward. Can you clarify your intent with this class?

2021-07-15 06:23 UTC, lucasmlofaro commented on operator_toolkit/check_auto.py
> +    def review_report(self, site, report):
The name of this method feels misleading to me. If the goal is separate sites into different sections of the report, maybe `add_to_section()` or something would make more sense.

2021-07-15 06:23 UTC, lucasmlofaro commented on operator_toolkit/check_auto.py
> +    report_manager.generate_summary(len(sites))
So my suspicion about the `AutoReportManager` class play out a bit here. This whole thing feels like it should be handled by the object instead of requiring a user to know the interface and define some procedure to properly construct the data. Remember, objects encapsulate data, so the question to ask is, "What data is this object responsible for?" In this case it seems to be that the intent is related to storing all of the sites we'd like to aggregate and generate reports for. You may have to refine that a bit, but with that understanding I have the following observations:

- Why not just pass the list of sites to the `AutoReportManager` and let the initializer handle this looping stuff?
- This `generate_report()` method is static because it is essentially being used as a constructor. May as well put the logic in the constructor directly or have a private helper instance method to help with generating the reports.
- The call to `review_report()` seems like it should just happen in `generate_report()`. Unless there's good reason for the report to **not** be reviewed after it generated, we shouldn't expect the user to have to perform the extra step.

2021-07-15 07:08 UTC, JulianaCP-v2 commented on operator_toolkit/check_auto.py
> +    report_manager.generate_summary(len(sites))
I love this feedback Lucas. Thanks for taking your time to analyze this. I totally agreed with your thoughts. (this and the ones above). I was feeling kind of uneasy with this as well, so thanks for helping me to improve this. About your suggestion, I didn't think about sending the whole list of sites before, (probably because in the other scripts I only send one site into the helper class) but this seems like a good option, going to implement it, thanks 👌

2021-07-15 19:28 UTC, lucasmlofaro requested changes
Overall this is **WAY** better, nice work @JulianaCP-v2! A few more tweaks and some additional design feedback, but this should be nearly ready.

2021-07-15 19:28 UTC, lucasmlofaro commented on operator_toolkit/check_auto.py
> +class AutoReportManager:
I'd still advocate for a name change on this class, could be something as simple as `SummaryReport`.

2021-07-15 19:28 UTC, lucasmlofaro commented on operator_toolkit/check_auto.py
> +        self._add_site_to_section(site, report.report)
One thing to think about, which maybe we don't need deal with now, is that `report.report` is kind of unfortunate semantics. Really we want to be asking the object for information _about_ its data instead of accessing its internal state. My point is that one solution to this would be to obfuscate data access by making the `Report` class itself subscriptable, or otherwise providing data access method (getters/setters), but that is against the spirit of OOP because it breaks encapsulation.

A better solution would be to make the `report` property completely internal to the class and exposing methods for relevant information. For example,
```python
report.pop("error", None)
```
isn't something the user should have to do, they should just have to ask,
```python
report.error()
```
and take action on its result. Any direct access to the data structure should be _encapsulated_ within the class.

Note that we have been using `Report` fairly generically up to this point, but starting to implement this kind of interface may require individual `Report` objects that are more particular to the kind of data they report. This is when you'd want (going back to an idea I had in an earlier comment) some kind of `Reportable` interface with the common methods for **all** reporting classes. We can discuss this design further if you're interested.

2021-07-15 19:28 UTC, lucasmlofaro commented on operator_toolkit/check_auto.py
> +    def analyze_sites(self):
So in the spirit of thinking about reports more generically, this really feels like a `display()` method to me for the more general `SummaryReport` object. I feel this way because all of the logic being invoked here ultimately is designed to trigger the underlying `display()` methods of the individual reports as well as the final summary data.

2021-07-15 19:40 UTC, JulianaCP-v2 commented on operator_toolkit/check_auto.py
> +        self._add_site_to_section(site, report.report)
thanks a lot for your feedback. Taking notes of everything. About this `Report` class I try to make some changes on PR #16 . Do you mind taking a look to the `Report` class there, and let me know your comments?

I basically try to make an interface of the `Report` class. So I remove the `__init__` and add the `site` and `report` parameters in the display method. (So we can just make something like `IgnoreCasesManager(Report, ABC):` if we want to implement the report in a class or make a custom report method.)

2021-07-15 20:14 UTC, JulianaCP-v2 commented on operator_toolkit/check_auto.py
> +    def analyze_sites(self):
mmm, this makes sense, I made some changes to the names and logic of the report class. Let me know if this has any sense for you. Also, I'm fine with changing the name but I would like to make a reference that this class handles summary reports of the `Auto` status of the site. So, wondering what do you think about something like `SummaryAutoStatusReport`? or any suggestions that do you have?

2021-07-16 00:17 UTC, lucasmlofaro requested changes
Hopefully this helps clarify what I'm thinking, let me know if you'd like to discuss on a call or soemthing.

2021-07-16 00:20 UTC, lucasmlofaro commented on operator_toolkit/operation/utils.py
> +                continue
You could get really fancy if you knew every site report would require a `ServiceManager`
def SiteReport(Reportable):
    def __init__(self, site, content):
        self._site = site
        self._manager = ServiceManager(site)
        super().__init__(self, content)

    def display():
        print(f"\n\n_____ Report on site: {site} _____")
        super().display()

class ForecastReport(SiteReport):
    def __init__(self, site):
        content = self._manager.forecast(self._forecast)
        super().__init__(self, site, content)

2021-07-16 00:22 UTC, JulianaCP-v2 commented on operator_toolkit/change_forecast.py
> +        super()._display(site, **report)
yes, actually I was thinking the same about this, but if we don't add  `def display(self, site, **report):` into the class (after we add the interface), pycharm shows a warning. So, maybe I just going to ignore this warning and remove this,  I prefer to remove this as well.

2021-07-16 00:25 UTC, lucasmlofaro commented on operator_toolkit/operation/utils.py
> +                continue
By the way, I think the "right" way to do this would be to define a second interface the encapsulates the site-specific nature of the object, the something like a `ForecastReport` would implement two different interfaces (so that we could avoid the subtyping), but that's maybe overkill right now.

2021-07-16 00:40 UTC, JulianaCP-v2 commented on operator_toolkit/change_forecast.py
> +        reportable._display(site, post_forecast=service_manager.forecast(self._forecast))
yeah sorry, didnt see this, This change was before making the class interface. Will update it, thanks

2021-07-19 18:37 UTC, lucasmlofaro approved these changes
I think this has reached a pretty good solid point. There's some additional work we can do, but for now I don't think the marginal value is worth it. This is already significantly better than where we started. I made one note about naming, but otherwise I think this is in good shape.

2021-07-19 18:37 UTC, lucasmlofaro commented on operator_toolkit/check_auto.py
> +        summary_reporter.add_site_to_summary(site, reporter.report())
So having `reporter.report()` seems like it's encapsulating data, but really it's just forcing you to call a method instead of accessing the data directly. I think it's OK for now, we can work on this more as we flesh things out, but ideally we'd be a bit more strict about encapsulating the data.

2021-07-19 18:37 UTC, lucasmlofaro commented on operator_toolkit/check_mode.py
> +        reporter = ModeReport(site, operation_type)
I think that these objects are supposed to be thought of as reports as opposed to reporters.

2021-07-19 23:06 UTC, merged