Config File
Axiom-Cloud-Inc/operator-toolkit pull request #3
Opened 2021-06-23 00:15 UTC by JulianaCP-v2

- config file to handle scripts added (list of all lcl, wf, cc, go sites, emerson and microthermo sites)
- some scripts deleted: (no longer used)
  - bound_change.py
  -  csv_schedule_sender.py
  - fleetwide_start_stop.py
  - get_forecast.py

2021-06-23 23:28 UTC, samhollenbach reviewed
2 comments about where to store the config file.

2021-06-23 23:28 UTC, samhollenbach commented on config.yaml
> +sites:
We really need a database for this stuff, but I would suggest at the least that we host this file in S3 (top level of the operations bucket) so at least we do not have to make code updates to change this file.

2021-06-23 23:28 UTC, samhollenbach commented on config.py
> +    return cabinets.read('config.yaml')
I would use an environment variable here, and as per my other comment it would be great if we could default to use an S3 path. What would be even better is actually to add some logic to try to use S3 (or ENV var) first, then fallback to this local file if that one can't be loaded.

2021-06-23 23:30 UTC, JulianaCP-v2 commented on config.yaml
> +sites:
mmm god idea. will do it

2021-06-24 00:17 UTC, dshen109 requested changes

2021-06-24 00:17 UTC, dshen109 commented on config.py
> +
Where does this get used? I don't see the reference.

2021-06-24 00:17 UTC, dshen109 commented on config.py
> +    return cabinets.read('config.yaml')
yaml should be `yml` extension based on our code conventions

2021-06-24 00:17 UTC, dshen109 commented on config.py
> +def sites(desired_sites, controller=None):
docstring for what this function does please -- its name is not descriptive

2021-06-24 01:17 UTC, JulianaCP-v2 commented on config.py
> +
it will be used in every script file in the `help` option when we define each `parser.add_argument`.

2021-06-24 01:33 UTC, dshen109 approved these changes

2021-06-24 01:38 UTC, samhollenbach requested changes
One change needed for proper error handling.

2021-06-24 01:38 UTC, samhollenbach commented on config.py
> +AWS_SECRET_ACCESS_KEY = os.environ.get("AWS_SECRET_ACCESS_KEY")
Generally I don't feel like these are essential to include, but it never hurts.

2021-06-24 01:38 UTC, samhollenbach commented on config.py
> +        return config
Need to wrap this in `try/except` with a general `Exception` (`except Exception as ex` and print out `ex`) instead of just checking `None`.

2021-06-24 14:40 UTC, JulianaCP-v2 commented on config.py
> +        return config
mmmm not sure why though. In the `load_file` function I have a `try/except` so any possible error should be handle, and then in the `load_config` i just checking if the `load_file` is returning anything different than `None`. First I try with S3 and then with a local file (if both failed, I raise an error)

2021-06-24 14:53 UTC, JulianaCP-v2 commented on config.py
> +        return config
not sure why thought. In the `load_file` I add a `try/except` so in theory this should never throw an error (just the content or None)

2021-06-24 22:06 UTC, samhollenbach commented on config.py
> +        print(ex)
Lets explicitly return `None` at the end of this function, for clarity.

2021-06-24 22:06 UTC, samhollenbach approved these changes
Looks good. One small change for clarity would help.

2021-06-29 15:43 UTC, merged