Check mode script
Axiom-Cloud-Inc/operator-toolkit pull request #4
Opened 2021-06-29 15:52 UTC by JulianaCP-v2

2021-06-30 20:49 UTC, jacksboo reviewed
Looks good to me only a couple recommended changes.

2021-06-30 20:49 UTC, jacksboo commented on operator_toolkit/check_mode.py
> +    application_mode = resp['application_mode'] if "application_mode" in resp else None
```suggestion
    application_mode = resp.get('application_mode', None)
```
Since `resp` is a dictionary and you only want to get the value of the key `application_mode` and if it doesn't exist return None as a value, this approach can be cleaner.

2021-06-30 20:49 UTC, jacksboo commented on operator_toolkit/check_mode.py
> +    url = f'http://{operation_type}-{site}.axiomcloud.io/report'
```suggestion
    url = f'https://{operation_type}-{site}.axiomcloud.io/report'
```

2021-07-01 17:16 UTC, samhollenbach requested changes

2021-07-01 17:16 UTC, samhollenbach commented on operator_toolkit/check_mode.py
> +        return {site: f"INVALID REQUEST! Message: {req.json()}"}
OK response seems like it should not exit with an error message.

2021-07-01 17:18 UTC, samhollenbach approved these changes
Didn't realize that was a `!=` instead of `==`. Looks good then. Maybe a comment there to make sure people realize this would help :)

2021-07-06 19:01 UTC, merged