Soc percentile script
Axiom-Cloud-Inc/operator-toolkit pull request #6
Opened 2021-06-29 16:20 UTC by JulianaCP-v2

2021-07-01 17:28 UTC, samhollenbach requested changes
A couple small things, nothing major.

2021-07-01 17:28 UTC, samhollenbach commented on config/operational-sites.yml
> +        multiplier: 0.65
Make sure these changes are propagated to S3

2021-07-01 17:28 UTC, samhollenbach commented on generated/README.md
> +Note: Files generated with the scripts.
?

2021-07-01 17:28 UTC, samhollenbach commented on operator_toolkit/create_soc_percentile.py
> +            reader = csv.reader(file)
Eventually this should live in S3 as well, and we can use `cabinets` CSV parser to parse it.

2021-07-01 17:28 UTC, samhollenbach commented on operator_toolkit/create_soc_percentile.py
> +    end = args.end.replace("T", " ")
Is this due to some specific datetime format parsing? I suggest using something like [arrow](https://arrow.readthedocs.io/en/latest/) to avoid these kinds of issues.

2021-07-01 17:28 UTC, samhollenbach commented on operator_toolkit/soc_helpers/loader.py
> +        :param end: end time, in ISO format.
```suggestion
        :param str site: site_id.
        :param str start: start time, in ISO format.
        :param str end: end time, in ISO format.
```
Specifying the `type` in these situations is helpful because there is some ambiguity whether or not this is a string representation of a datetime, or a `datetime` object, or an `Arrow` object, etc.

2021-07-01 17:28 UTC, samhollenbach commented on operator_toolkit/soc_helpers/loader.py
> +                    f"WHERE ({where}) GROUP BY time({interval}) ORDER BY desc"
When doing multiline strings it's nice to use the `"""` style string blocks instead of the ugly `\`.

2021-07-01 17:28 UTC, samhollenbach commented on operator_toolkit/soc_helpers/loader.py
> +                                 timeout=CONFIG["influxdb_client"]["timeout"])
If these are the only keys in that dictionary, you could do this :)
```suggestion
        client = DataFrameClient(username=os.environ['INFLUXDB_USERNAME'],
                                 password=os.environ['INFLUXDB_PASSWORD'],
                                 **CONFIG["influxdb_client"]])
```

2021-07-01 17:31 UTC, JulianaCP-v2 commented on config/operational-sites.yml
> +        multiplier: 0.65
yes 👌, going to update the file when we have the last status of the file. For now the file is changing so waiting for an stable version to update it

2021-07-01 17:32 UTC, JulianaCP-v2 commented on generated/README.md
> +Note: Files generated with the scripts.
basically, I want to keep in the repo the `generated` folder. So we can have a reference of where the files generated for the scripts are going to be located, but we cant add an empty folder to the repo, so I added a readme to make reference that there we are going to saved the files generated by the scripts

2021-07-01 17:34 UTC, JulianaCP-v2 commented on operator_toolkit/create_soc_percentile.py
> +            reader = csv.reader(file)
thats great. i didnt know we can use cabinets, didn't see a reference in the docs, but going to try it.

2021-07-01 17:38 UTC, JulianaCP-v2 commented on operator_toolkit/create_soc_percentile.py
> +    end = args.end.replace("T", " ")
yes, in fact, I use it to handle args values, seems we can not leave an empty space and just a continuous string, I used `T` to make a reference to the time. Actually, I tried using arrow but arrow takes timezone reference when we loaded the date (we don't need it), so we will have to parse in order to extract just the date and the time. So I thought it will be simple just to remove the "T" from the date string that the users sent in the `args` values. I can change it if you prefer it though, let me know

2021-07-01 17:39 UTC, JulianaCP-v2 commented on operator_toolkit/soc_helpers/loader.py
> +        :param end: end time, in ISO format.
agreed! totally missed this, thanks

2021-07-01 17:44 UTC, JulianaCP-v2 commented on operator_toolkit/soc_helpers/loader.py
> +                                 timeout=CONFIG["influxdb_client"]["timeout"])
thanks, going to try it. Im not sure if is going to work though seems `influxdb_client` have more configurations that the ones that `DataFrameClient` need, so not sure if its going to though an error, but I'm totally going to try it 👌

2021-07-01 17:46 UTC, JulianaCP-v2 commented on operator_toolkit/soc_helpers/loader.py
> +                                 timeout=CONFIG["influxdb_client"]["timeout"])
actually there are more keys than these ones. The `client.query` option uses a couple of more keys from that config dict

2021-07-02 17:07 UTC, samhollenbach commented on generated/README.md
> +Note: Files generated with the scripts.
Ok makes sense, can you add a little bit more information to this README then? Just with the same info you have in this comment.

2021-07-02 17:11 UTC, samhollenbach commented on operator_toolkit/create_soc_percentile.py
> +            reader = csv.reader(file)
Yeah the CSV parser is still somewhat in Beta (not very configurable), so be careful using it. This is more for future reference.

2021-07-02 17:15 UTC, samhollenbach commented on operator_toolkit/create_soc_percentile.py
> +    end = args.end.replace("T", " ")
I think we should try to use arrow still, and be more careful about what timezone we are using. In general, all datetimes should be timezone aware, or else we can lead to scary issues (sites in different timezones, etc). By default we should be defaulting the timezone to the users local time (which is what Python does with `datetime` objects). Timezone stuff is tricky, but it's important to have it included.

2021-07-02 17:16 UTC, samhollenbach commented on operator_toolkit/soc_helpers/loader.py
> +                                 timeout=CONFIG["influxdb_client"]["timeout"])
Yeah I actually see that now in the lines below this comment. Could be an argument for reorganizing the configuration, but this is totally fine for now.

2021-07-02 17:19 UTC, samhollenbach reviewed
A couple comments. The biggest thing I think we should be careful with is time zones. It's not absolutely essential that we use proper time zone-aware datetimes in this script, but I think it's really good practice for us to always use them. We've run into time zone issues countless times, so getting everyone familiar and comfortable with `arrow` / `pytz` / Python 3.10 time zone features is extremely useful. If getting this script merged in isn't urgent, I would love to see you try again with time zone aware datetimes. I'm happy to meet with you to discuss how to do this if you get stuck.

2021-07-06 17:22 UTC, samhollenbach requested changes
Very small changes, but looks pretty good.

2021-07-06 17:22 UTC, samhollenbach commented on config/operational-sites.yml
> +        multiplier: 0.65
I actually think `multiplier` is a pretty vague name here. I would prefer something with more obvious meaning just from looking at this file.

2021-07-06 17:22 UTC, samhollenbach commented on operator_toolkit/soc_helpers/config.yml
> +  - rack.*.SoC_.*_percentile$
The more explicit regex would look like:
```suggestion
  - rack\d+\.sg\d+\.SoC_.*_percentile$
```

2021-07-06 17:22 UTC, samhollenbach commented on operator_toolkit/create_soc_percentile.py
> +    SoCs = soc_percentile.sites_socs(sites_to_operate, start, end, args.timezone)
It seems like the nicer thing to do here is either pass around `Arrow` or `datetime` objects to these functions directly, and do string formatting within the methods. I try to avoid using string datetimes anywhere I can. 

On another note, you may be able to use [Arrow.isoformat()](https://arrow.readthedocs.io/en/latest/#arrow.arrow.Arrow.isoformat) instead of `.datetime.strftime(...)` here.

2021-07-06 18:55 UTC, samhollenbach approved these changes

2021-07-06 18:57 UTC, merged