Ephemeral rules script
Axiom-Cloud-Inc/operator-toolkit pull request #9
Opened 2021-07-06 23:23 UTC by JulianaCP-v2

2021-07-07 23:33 UTC, lucasmlofaro requested changes
Looks pretty good, a couple of minor things.

2021-07-07 23:33 UTC, lucasmlofaro commented on operator_toolkit/create_soc_percentile.py
> +    def create_schedule(self, sites_to_operate, schedule_datetime):
Is there a better name than `schedule_datetime`? Like is this the start of the schedule or is there some other descriptive term we could use?

2021-07-07 23:33 UTC, lucasmlofaro commented on operator_toolkit/create_soc_percentile.py
> +    def create_schedule(self, sites_to_operate, schedule_datetime):
Aha, it's in the help text
```
End time of the operation
```
Maybe `end_time` is good enough, but open to suggestions.

2021-07-07 23:33 UTC, lucasmlofaro commented on operator_toolkit/ephemeral_bound_schedule.py
> +)
```suggestion
from common import (
    AXIOM_API_AUTH_USER,
    AXIOM_API_AUTH_PASSWORD,
    CLI_MESSAGE,
    ServiceType,
    sites,
    load_file,
    basic_url,
)
```

2021-07-07 23:33 UTC, lucasmlofaro commented on operator_toolkit/ephemeral_bound_schedule.py
> +def create_ephemeral_schedule(site, start, stop, bound_multiplier, soc_25_percentile):
Perhaps just a note for later, but this feels to me like it should be a method in a class. I'm wondering if we should schedule some time to go through all the scripts and decide on a better data model for some of these things.

2021-07-07 23:33 UTC, lucasmlofaro commented on operator_toolkit/create_soc_percentile.py
> +    def create_schedule(self, sites_to_operate, schedule_datetime):
Looks like we just use `end` in the other script from this PR.

2021-07-07 23:38 UTC, JulianaCP-v2 commented on operator_toolkit/create_soc_percentile.py
> +    def create_schedule(self, sites_to_operate, schedule_datetime):
good catch! I copy and paste the help description from the previous `end` args param and I forgot to update this one. in theory, this `schedule_datetime` is a different value from `start` or `end` datetimes. This specifically is used to create a `schedule.csv` file.

2021-07-07 23:41 UTC, JulianaCP-v2 commented on operator_toolkit/ephemeral_bound_schedule.py
> +def create_ephemeral_schedule(site, start, stop, bound_multiplier, soc_25_percentile):
yes, definitely. I'm feeling the same as you. In this next sprint, I'm thinking about creating some classes to process these scripts so we can improve in general the process (re use code, etc)

2021-07-07 23:55 UTC, JulianaCP-v2 commented on operator_toolkit/create_soc_percentile.py
> +    def create_schedule(self, sites_to_operate, schedule_datetime):
Actually I just spoke with Eliav, he told me he doesn't need that schedule csv file any more, So I'm just going to remove all related code with that

2021-07-09 18:13 UTC, lucasmlofaro approved these changes

2021-07-09 18:13 UTC, merged